/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthedTabsRouteImport } from './routes/_authed/_tabs'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthedTabsIndexRouteImport } from './routes/_authed/_tabs/index'
import { Route as AuthedQuizPremadeRouteImport } from './routes/_authed/quiz/premade'
import { Route as AuthedQuizPlayRouteImport } from './routes/_authed/quiz/play'
import { Route as AuthedQuizLoadingRouteImport } from './routes/_authed/quiz/loading'
import { Route as AuthedQuizAiLoadingRouteImport } from './routes/_authed/quiz/ai-loading'
import { Route as AuthedQuizChapterIdRouteImport } from './routes/_authed/quiz/$chapterId'
import { Route as AuthedChapterBookIdRouteImport } from './routes/_authed/chapter/$bookId'
import { Route as AuthedTabsSettingsRouteImport } from './routes/_authed/_tabs/settings'
import { Route as AuthedTabsBooksRouteImport } from './routes/_authed/_tabs/books'
import { Route as AuthedChapterChapterIdVocabularyRouteImport } from './routes/_authed/chapter/$chapterId/vocabulary'
import { Route as AuthedChapterChapterIdGrammarRouteImport } from './routes/_authed/chapter/$chapterId/grammar'
import { Route as AuthedChapterChapterIdDialoguesRouteImport } from './routes/_authed/chapter/$chapterId/dialogues'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTabsRoute = AuthedTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedTabsIndexRoute = AuthedTabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedTabsRoute,
} as any)
const AuthedQuizPremadeRoute = AuthedQuizPremadeRouteImport.update({
  id: '/quiz/premade',
  path: '/quiz/premade',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQuizPlayRoute = AuthedQuizPlayRouteImport.update({
  id: '/quiz/play',
  path: '/quiz/play',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQuizLoadingRoute = AuthedQuizLoadingRouteImport.update({
  id: '/quiz/loading',
  path: '/quiz/loading',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQuizAiLoadingRoute = AuthedQuizAiLoadingRouteImport.update({
  id: '/quiz/ai-loading',
  path: '/quiz/ai-loading',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQuizChapterIdRoute = AuthedQuizChapterIdRouteImport.update({
  id: '/quiz/$chapterId',
  path: '/quiz/$chapterId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChapterBookIdRoute = AuthedChapterBookIdRouteImport.update({
  id: '/chapter/$bookId',
  path: '/chapter/$bookId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTabsSettingsRoute = AuthedTabsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedTabsRoute,
} as any)
const AuthedTabsBooksRoute = AuthedTabsBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthedTabsRoute,
} as any)
const AuthedChapterChapterIdVocabularyRoute =
  AuthedChapterChapterIdVocabularyRouteImport.update({
    id: '/chapter/$chapterId/vocabulary',
    path: '/chapter/$chapterId/vocabulary',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedChapterChapterIdGrammarRoute =
  AuthedChapterChapterIdGrammarRouteImport.update({
    id: '/chapter/$chapterId/grammar',
    path: '/chapter/$chapterId/grammar',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedChapterChapterIdDialoguesRoute =
  AuthedChapterChapterIdDialoguesRouteImport.update({
    id: '/chapter/$chapterId/dialogues',
    path: '/chapter/$chapterId/dialogues',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedTabsIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/books': typeof AuthedTabsBooksRoute
  '/settings': typeof AuthedTabsSettingsRoute
  '/chapter/$bookId': typeof AuthedChapterBookIdRoute
  '/quiz/$chapterId': typeof AuthedQuizChapterIdRoute
  '/quiz/ai-loading': typeof AuthedQuizAiLoadingRoute
  '/quiz/loading': typeof AuthedQuizLoadingRoute
  '/quiz/play': typeof AuthedQuizPlayRoute
  '/quiz/premade': typeof AuthedQuizPremadeRoute
  '/chapter/$chapterId/dialogues': typeof AuthedChapterChapterIdDialoguesRoute
  '/chapter/$chapterId/grammar': typeof AuthedChapterChapterIdGrammarRoute
  '/chapter/$chapterId/vocabulary': typeof AuthedChapterChapterIdVocabularyRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedTabsIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/books': typeof AuthedTabsBooksRoute
  '/settings': typeof AuthedTabsSettingsRoute
  '/chapter/$bookId': typeof AuthedChapterBookIdRoute
  '/quiz/$chapterId': typeof AuthedQuizChapterIdRoute
  '/quiz/ai-loading': typeof AuthedQuizAiLoadingRoute
  '/quiz/loading': typeof AuthedQuizLoadingRoute
  '/quiz/play': typeof AuthedQuizPlayRoute
  '/quiz/premade': typeof AuthedQuizPremadeRoute
  '/chapter/$chapterId/dialogues': typeof AuthedChapterChapterIdDialoguesRoute
  '/chapter/$chapterId/grammar': typeof AuthedChapterChapterIdGrammarRoute
  '/chapter/$chapterId/vocabulary': typeof AuthedChapterChapterIdVocabularyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authed/_tabs': typeof AuthedTabsRouteWithChildren
  '/_authed/_tabs/books': typeof AuthedTabsBooksRoute
  '/_authed/_tabs/settings': typeof AuthedTabsSettingsRoute
  '/_authed/chapter/$bookId': typeof AuthedChapterBookIdRoute
  '/_authed/quiz/$chapterId': typeof AuthedQuizChapterIdRoute
  '/_authed/quiz/ai-loading': typeof AuthedQuizAiLoadingRoute
  '/_authed/quiz/loading': typeof AuthedQuizLoadingRoute
  '/_authed/quiz/play': typeof AuthedQuizPlayRoute
  '/_authed/quiz/premade': typeof AuthedQuizPremadeRoute
  '/_authed/_tabs/': typeof AuthedTabsIndexRoute
  '/_authed/chapter/$chapterId/dialogues': typeof AuthedChapterChapterIdDialoguesRoute
  '/_authed/chapter/$chapterId/grammar': typeof AuthedChapterChapterIdGrammarRoute
  '/_authed/chapter/$chapterId/vocabulary': typeof AuthedChapterChapterIdVocabularyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/books'
    | '/settings'
    | '/chapter/$bookId'
    | '/quiz/$chapterId'
    | '/quiz/ai-loading'
    | '/quiz/loading'
    | '/quiz/play'
    | '/quiz/premade'
    | '/chapter/$chapterId/dialogues'
    | '/chapter/$chapterId/grammar'
    | '/chapter/$chapterId/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/books'
    | '/settings'
    | '/chapter/$bookId'
    | '/quiz/$chapterId'
    | '/quiz/ai-loading'
    | '/quiz/loading'
    | '/quiz/play'
    | '/quiz/premade'
    | '/chapter/$chapterId/dialogues'
    | '/chapter/$chapterId/grammar'
    | '/chapter/$chapterId/vocabulary'
  id:
    | '__root__'
    | '/_auth'
    | '/_authed'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_authed/_tabs'
    | '/_authed/_tabs/books'
    | '/_authed/_tabs/settings'
    | '/_authed/chapter/$bookId'
    | '/_authed/quiz/$chapterId'
    | '/_authed/quiz/ai-loading'
    | '/_authed/quiz/loading'
    | '/_authed/quiz/play'
    | '/_authed/quiz/premade'
    | '/_authed/_tabs/'
    | '/_authed/chapter/$chapterId/dialogues'
    | '/_authed/chapter/$chapterId/grammar'
    | '/_authed/chapter/$chapterId/vocabulary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_tabs': {
      id: '/_authed/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedTabsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/_tabs/': {
      id: '/_authed/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedTabsIndexRouteImport
      parentRoute: typeof AuthedTabsRoute
    }
    '/_authed/quiz/premade': {
      id: '/_authed/quiz/premade'
      path: '/quiz/premade'
      fullPath: '/quiz/premade'
      preLoaderRoute: typeof AuthedQuizPremadeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/quiz/play': {
      id: '/_authed/quiz/play'
      path: '/quiz/play'
      fullPath: '/quiz/play'
      preLoaderRoute: typeof AuthedQuizPlayRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/quiz/loading': {
      id: '/_authed/quiz/loading'
      path: '/quiz/loading'
      fullPath: '/quiz/loading'
      preLoaderRoute: typeof AuthedQuizLoadingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/quiz/ai-loading': {
      id: '/_authed/quiz/ai-loading'
      path: '/quiz/ai-loading'
      fullPath: '/quiz/ai-loading'
      preLoaderRoute: typeof AuthedQuizAiLoadingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/quiz/$chapterId': {
      id: '/_authed/quiz/$chapterId'
      path: '/quiz/$chapterId'
      fullPath: '/quiz/$chapterId'
      preLoaderRoute: typeof AuthedQuizChapterIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chapter/$bookId': {
      id: '/_authed/chapter/$bookId'
      path: '/chapter/$bookId'
      fullPath: '/chapter/$bookId'
      preLoaderRoute: typeof AuthedChapterBookIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_tabs/settings': {
      id: '/_authed/_tabs/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedTabsSettingsRouteImport
      parentRoute: typeof AuthedTabsRoute
    }
    '/_authed/_tabs/books': {
      id: '/_authed/_tabs/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthedTabsBooksRouteImport
      parentRoute: typeof AuthedTabsRoute
    }
    '/_authed/chapter/$chapterId/vocabulary': {
      id: '/_authed/chapter/$chapterId/vocabulary'
      path: '/chapter/$chapterId/vocabulary'
      fullPath: '/chapter/$chapterId/vocabulary'
      preLoaderRoute: typeof AuthedChapterChapterIdVocabularyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chapter/$chapterId/grammar': {
      id: '/_authed/chapter/$chapterId/grammar'
      path: '/chapter/$chapterId/grammar'
      fullPath: '/chapter/$chapterId/grammar'
      preLoaderRoute: typeof AuthedChapterChapterIdGrammarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chapter/$chapterId/dialogues': {
      id: '/_authed/chapter/$chapterId/dialogues'
      path: '/chapter/$chapterId/dialogues'
      fullPath: '/chapter/$chapterId/dialogues'
      preLoaderRoute: typeof AuthedChapterChapterIdDialoguesRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedTabsRouteChildren {
  AuthedTabsBooksRoute: typeof AuthedTabsBooksRoute
  AuthedTabsSettingsRoute: typeof AuthedTabsSettingsRoute
  AuthedTabsIndexRoute: typeof AuthedTabsIndexRoute
}

const AuthedTabsRouteChildren: AuthedTabsRouteChildren = {
  AuthedTabsBooksRoute: AuthedTabsBooksRoute,
  AuthedTabsSettingsRoute: AuthedTabsSettingsRoute,
  AuthedTabsIndexRoute: AuthedTabsIndexRoute,
}

const AuthedTabsRouteWithChildren = AuthedTabsRoute._addFileChildren(
  AuthedTabsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedTabsRoute: typeof AuthedTabsRouteWithChildren
  AuthedChapterBookIdRoute: typeof AuthedChapterBookIdRoute
  AuthedQuizChapterIdRoute: typeof AuthedQuizChapterIdRoute
  AuthedQuizAiLoadingRoute: typeof AuthedQuizAiLoadingRoute
  AuthedQuizLoadingRoute: typeof AuthedQuizLoadingRoute
  AuthedQuizPlayRoute: typeof AuthedQuizPlayRoute
  AuthedQuizPremadeRoute: typeof AuthedQuizPremadeRoute
  AuthedChapterChapterIdDialoguesRoute: typeof AuthedChapterChapterIdDialoguesRoute
  AuthedChapterChapterIdGrammarRoute: typeof AuthedChapterChapterIdGrammarRoute
  AuthedChapterChapterIdVocabularyRoute: typeof AuthedChapterChapterIdVocabularyRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedTabsRoute: AuthedTabsRouteWithChildren,
  AuthedChapterBookIdRoute: AuthedChapterBookIdRoute,
  AuthedQuizChapterIdRoute: AuthedQuizChapterIdRoute,
  AuthedQuizAiLoadingRoute: AuthedQuizAiLoadingRoute,
  AuthedQuizLoadingRoute: AuthedQuizLoadingRoute,
  AuthedQuizPlayRoute: AuthedQuizPlayRoute,
  AuthedQuizPremadeRoute: AuthedQuizPremadeRoute,
  AuthedChapterChapterIdDialoguesRoute: AuthedChapterChapterIdDialoguesRoute,
  AuthedChapterChapterIdGrammarRoute: AuthedChapterChapterIdGrammarRoute,
  AuthedChapterChapterIdVocabularyRoute: AuthedChapterChapterIdVocabularyRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
